import type { Metadata } from 'next';
import './globals.css';
import { Inter, DM_Sans } from 'next/font/google';
import Navigation from './_components/Navigation';
import Footer from './_components/Footer';

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
});

const dm_sans = DM_Sans({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-dm_sans',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${dm_sans.variable} antialiased`}>
        <div className="container mx-auto pt-4">
          <Navigation />
        </div>
        {children}
        <Footer />
      </body>
    </html>
  );
}
