import type { Metadata } from 'next';
import './globals.css';
import { Inter, DM_Sans } from 'next/font/google';
import Navigation from './_components/Navigation';

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
});

const dm_sans = DM_Sans({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-dm_sans',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} ${dm_sans.variable} antialiased pb-[200px]`}
      >
        <div className="bg-slate-500 pt-4">
          <div className="container mx-auto">
            <Navigation />
            <div className="h-[calc(573px+24px)] pt-[72px] pb-[55px]"></div>
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
